name: hidden_city
description: ta.fti.bjm.ac.id

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.4.2+3

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  build_runner: ^2.1.11
  camera: ^0.10.0
  chess: ^0.7.0
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  dbcrypt: ^2.0.0
  dio: ^4.0.6
  firebase_auth: ^3.6.2
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.12
  fl_chart: ^0.55.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.5
  google_sign_in: ^5.4.1
  hive: ^2.2.1
  hive_generator: ^1.1.3
  http: ^0.13.4
  image: ^3.2.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.5+3
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pdf: ^3.8.1
  provider: ^6.0.3
  tflite: ^1.1.2
  url_launcher: ^6.0.20
  video_player: ^2.4.2
  wave: ^0.2.2
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/audio/
    - assets/ai/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoI
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
    - family: RobotoB
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
    - family: TechnoBoard
      fonts:
        - asset: assets/fonts/TechnoBoard.ttf
    - family: Scramble
      fonts:
        - asset: assets/fonts/scram.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 7
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
